// <auto-generated />
using BairroConnectAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BairroConnectAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BairroConnectAPI.Models.Logins", b =>
                {
                    b.Property<int>("idPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPessoa"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipoConta")
                        .HasColumnType("int");

                    b.HasKey("idPessoa");

                    b.ToTable("TB_LOGINS");

                    b.HasData(
                        new
                        {
                            idPessoa = 1,
                            email = "carlos.e.789999@gmail.com",
                            nome = "Carlos",
                            sobrenome = "Silva",
                            tipoConta = 1
                        },
                        new
                        {
                            idPessoa = 2,
                            email = "daniel.silva@gmail.com",
                            nome = "Daniel",
                            sobrenome = "Silva",
                            tipoConta = 1
                        },
                        new
                        {
                            idPessoa = 3,
                            email = "teste.e.@gmail.com",
                            nome = "teste",
                            sobrenome = "teste",
                            tipoConta = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
